"""empty message

Revision ID: 0b18572eb155
Revises: d6e31cb7b40c
Create Date: 2024-06-22 09:49:19.490990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b18572eb155'
down_revision: Union[str, None] = 'd6e31cb7b40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_status_id_fkey', 'movie', type_='foreignkey')
    op.drop_column('movie', 'status_id')
    op.add_column('status', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'status', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.drop_column('status', 'movie_id')
    op.add_column('movie', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movie_status_id_fkey', 'movie', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###
