"""add tables

Revision ID: 696c4734edff
Revises: a734d48e9b30
Create Date: 2024-06-19 23:15:24.913282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696c4734edff'
down_revision: Union[str, None] = 'a734d48e9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ru_title', sa.String(), nullable=True),
    sa.Column('en_title', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('description_short', sa.String(), nullable=True),
    sa.Column('description_all', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('episode_all', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('studio', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('count_rating', sa.String(), nullable=True),
    sa.Column('adding_time', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('href')
    )
    op.create_table('association_movie_category',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'category_id')
    )
    op.create_table('association_movie_voice',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'voice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_movie_voice')
    op.drop_table('association_movie_category')
    op.drop_table('movie')
    op.drop_table('voice_movie')
    op.drop_table('type_movie')
    op.drop_table('status')
    op.drop_table('category')
    # ### end Alembic commands ###
